version: '3'


services:

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
    

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3001
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=${NATS_SERVERS}

  usuarios-ms:
    build: ./usuarios-ms
    volumes:
      - ./usuarios-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}

  auth-ms:
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
  
  aplicaciones-ms:
    build: ./proyectos-ms
    volumes:
      - ./proyectos-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - APP_MS_PORT=3004
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - PATH_PROJECTS=${PATH_PROJECTS}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}


  rviami-ms:
    build: ./rviami-ms
    volumes:
      - ./rviami-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3005
      - NATS_SERVERS=${NATS_SERVERS}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}

  rviasa-ms:
    build: ./rviasa-ms
    volumes:
      - ./rviasa-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3006
      - NATS_SERVERS=${NATS_SERVERS}
      - SECRET_KEY=${SECRET_KEY}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}

  rviaca-ms:
    build: ./rviaca-ms
    volumes:
      - ./rviaca-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3007
      - NATS_SERVERS=${NATS_SERVERS}
      - SECRET_KEY=${SECRET_KEY}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}


  rviacp-ms:
    build: ./rviacp-ms
    volumes:
      - ./rviacp-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3008
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - SECRET_KEY=${SECRET_KEY}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}

  rviaco-ms:
    build: ./rviaco-ms
    volumes:
      - ./rviaco-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3009
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

  rviaac-ms:
    build: ./rviaac-ms
    volumes:
      - ./rviaac-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3010
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}


  lenguajes-ms:
    build: ./lenguajes-ms
    volumes:
      - ./lenguajes-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3011
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}

  rviadoc-ms:
    build: ./rviadoc-ms
    volumes:
      - ./rviadoc-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3011
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}

  rviacal-ms:
    build: ./rviacal-ms
    volumes:
      - ./rviacal-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3011
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}

  rviaprodoc-ms:
    build: ./rviaprodoc-ms
    volumes:
      - ./rviaprodoc-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3011
      - NATS_SERVERS=${NATS_SERVERS}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - RVIA_ENVIRONMENT=${RVIA_ENVIRONMENT}
      - RVIA_PATH=${RVIA_PATH}
      - PATH_PROJECT=${PATH_PROJECTS}